<a href="https://colab.research.google.com/github/taisriquinho/Curso-Machine-Learning-/blob/main/04-KNN/KNN_Classificacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
data = pd.read_table('fruit_data_with_colors.txt')

In [ ]:
data

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [ ]:
X = data[['mass','height','width','color_score']]
y = data[['fruit_label']]

In [ ]:
X

    mass  height  width  color_score
0    192     7.3    8.4         0.55
1    180     6.8    8.0         0.59
2    176     7.2    7.4         0.60
3     86     4.7    6.2         0.80
4     84     4.6    6.0         0.79
5     80     4.3    5.8         0.77
6     80     4.3    5.9         0.81
7     76     4.0    5.8         0.81
8    178     7.8    7.1         0.92
9    172     7.0    7.4         0.89
10   166     7.3    6.9         0.93
11   172     7.6    7.1         0.92
12   154     7.1    7.0         0.88
13   164     7.7    7.3         0.70
14   152     7.3    7.6         0.69
15   156     7.1    7.7         0.69
16   156     7.5    7.6         0.67
17   168     7.6    7.5         0.73
18   162     7.1    7.5         0.83
19   162     7.2    7.4         0.85
20   160     7.5    7.5         0.86
21   156     7.4    7.4         0.84
22   140     7.1    7.3         0.87
23   170     7.9    7.6         0.88
24   342     9.4    9.0         0.75
25   356     9.2    9.2         0.75
26   362     9.2    9.6         0.74
27   204     9.2    7.5         0.77
28   140     7.1    6.7         0.72
29   160     7.4    7.0         0.81
30   158     7.5    7.1         0.79
31   210     8.0    7.8         0.82
32   164     7.0    7.2         0.80
33   190     8.1    7.5         0.74
34   142     7.8    7.6         0.75
35   150     7.9    7.1         0.75
36   160     7.6    7.1         0.76
37   154     7.3    7.3         0.79
38   158     7.8    7.2         0.77
39   144     7.4    6.8         0.75
40   154     7.5    7.1         0.78
41   180     8.2    7.6         0.79
42   154     7.2    7.2         0.82
43   194    10.3    7.2         0.70
44   200    10.5    7.3         0.72
45   186     9.2    7.2         0.72
46   216    10.2    7.3         0.71
47   196     9.7    7.3         0.72
48   174    10.1    7.3         0.72
49   132     8.7    5.8         0.73
50   130     8.2    6.0         0.71
51   116     7.5    6.0         0.72
52   118     8.0    5.9         0.72
53   120     8.4    6.0         0.74
54   116     8.5    6.1         0.71
55   116     7.7    6.3         0.72
56   116     8.1    5.9         0.73
57   152     8.5    6.5         0.72
58   118     8.1    6.1         0.70

In [ ]:
y

    fruit_label
0             1
1             1
2             1
3             2
4             2
5             2
6             2
7             2
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            3
25            3
26            3
27            3
28            3
29            3
30            3
31            3
32            3
33            3
34            3
35            3
36            3
37            3
38            3
39            3
40            3
41            3
42            3
43            4
44            4
45            4
46            4
47            4
48            4
49            4
50            4
51            4
52            4
53            4
54            4
55            4
56            4
57            4
58            4

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [ ]:
knn.fit(X_train, Y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.score(X_test, y_test)

0.6

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mm = MinMaxScaler()

In [ ]:
X_train = mm.fit_transform(X_train)

In [ ]:
X_train

array([[0.32624113, 0.53225806, 0.34210526, 0.97368421],
       [0.28368794, 0.51612903, 0.44736842, 0.81578947],
       [0.21276596, 0.4516129 , 0.39473684, 0.84210526],
       [0.13475177, 0.61290323, 0.07894737, 0.39473684],
       [1.        , 0.79032258, 1.        , 0.5       ],
       [0.30496454, 0.48387097, 0.28947368, 1.        ],
       [0.34751773, 0.56451613, 0.34210526, 0.97368421],
       [0.35460993, 0.62903226, 0.47368421, 0.63157895],
       [0.34042553, 0.46774194, 0.42105263, 0.13157895],
       [0.14184397, 0.66129032, 0.05263158, 0.5       ],
       [0.31205674, 0.53225806, 0.44736842, 0.47368421],
       [0.26950355, 0.4516129 , 0.5       , 0.36842105],
       [0.31914894, 0.58064516, 0.47368421, 0.86842105],
       [0.26241135, 0.51612903, 0.34210526, 0.60526316],
       [0.92907801, 0.82258065, 0.84210526, 0.52631579],
       [0.18439716, 0.70967742, 0.        , 0.47368421],
       [0.26241135, 0.48387097, 0.39473684, 0.63157895],
       [0.9787234 , 0.79032258, 0.89473684, 0.52631579],
       [0.26241135, 0.46774194, 0.36842105, 0.71052632],
       [0.21276596, 0.4516129 , 0.23684211, 0.44736842],
       [0.12765957, 0.61290323, 0.02631579, 0.47368421],
       [0.22695035, 0.5       , 0.26315789, 0.52631579],
       [0.32624113, 0.43548387, 0.42105263, 0.89473684],
       [0.28368794, 0.53225806, 0.34210526, 0.55263158],
       [0.39716312, 0.48387097, 0.68421053, 0.        ],
       [0.27659574, 0.56451613, 0.36842105, 0.57894737],
       [0.39007092, 0.61290323, 0.44736842, 0.5       ],
       [0.29787234, 0.43548387, 0.36842105, 0.65789474],
       [0.26950355, 0.5       , 0.42105263, 0.76315789],
       [0.41134752, 0.87096774, 0.39473684, 0.44736842],
       [0.        , 0.        , 0.02631579, 0.68421053],
       [0.        , 0.        , 0.        , 0.57894737],
       [0.35460993, 0.40322581, 0.57894737, 0.10526316],
       [0.28368794, 0.5       , 0.31578947, 0.68421053],
       [0.0212766 , 0.06451613, 0.10526316, 0.65789474],
       [0.40425532, 0.96774194, 0.36842105, 0.39473684],
       [0.25531915, 0.67741935, 0.18421053, 0.44736842],
       [0.37588652, 0.79032258, 0.36842105, 0.44736842],
       [0.42553191, 1.        , 0.39473684, 0.44736842],
       [0.33333333, 0.93548387, 0.39473684, 0.44736842],
       [0.21985816, 0.56451613, 0.47368421, 0.52631579],
       [0.4822695 , 0.9516129 , 0.39473684, 0.42105263],
       [0.27659574, 0.51612903, 0.34210526, 0.63157895],
       [0.25531915, 0.48387097, 0.47368421, 0.36842105]])

In [ ]:
X_test = mm.transform(X_test)

In [ ]:
X_test

array([[ 0.46099291,  0.59677419,  0.52631579,  0.71052632],
       [ 0.26241135,  0.4516129 ,  0.31578947,  0.86842105],
       [ 0.24822695,  0.58064516,  0.34210526,  0.52631579],
       [ 0.13475177,  0.59677419,  0.02631579,  0.44736842],
       [ 0.29078014,  0.46774194,  0.42105263,  0.78947368],
       [-0.0141844 , -0.0483871 ,  0.        ,  0.68421053],
       [ 0.0141844 ,  0.0483871 ,  0.05263158,  0.63157895],
       [ 0.43971631,  0.79032258,  0.44736842,  0.57894737],
       [ 0.29078014,  0.4516129 ,  0.44736842,  0.73684211],
       [ 0.12765957,  0.67741935,  0.07894737,  0.42105263],
       [ 0.29787234,  0.5483871 ,  0.39473684,  0.39473684],
       [ 0.12765957,  0.51612903,  0.05263158,  0.44736842],
       [ 0.17730496,  0.62903226,  0.05263158,  0.42105263],
       [ 0.26950355,  0.51612903,  0.47368421,  0.31578947],
       [ 0.12765957,  0.5483871 ,  0.13157895,  0.44736842]])

In [ ]:
knn = KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
knn.score(X_test, y_test)

0.8666666666666667

In [ ]:
knn.predict(X_test)

array([1, 1, 3, 4, 1, 2, 2, 4, 1, 4, 1, 4, 4, 1, 4])

In [ ]:
y_test

    fruit_label
31            3
12            1
35            3
52            4
19            1
7             2
4             2
27            3
18            1
54            4
13            1
51            4
50            4
16            1
55            4